version: '3'

services:
    
  ipfs-kubo:
    image: ipfs/kubo:v0.19.1
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"
    volumes:
      - ipfs-data:/data/ipfs
      
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '4306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - "./sql-scripts/data.sql:/docker-entrypoint-initdb.d/1.sql"

  ganache:
   image: trufflesuite/ganache-cli:latest
   command: ganache-cli --port 8545 --networkId 5777 --mnemonic "kerem halil istanbul bitirme proje"
   ports:
     - "127.0.0.1:7545:8545"
    

volumes:
  ipfs-data:
  mysql-data: